<?php
/** @var Mage_Core_Block_Template $this */
/** @var Omikron_Factfinder_Helper_Data $dataHelper */
$dataHelper = Mage::helper('factfinder/data');

// It returns advisor and feedback campaign if enabled
if ($dataHelper->getFFCampaign()):
    echo $this->getChildHtml('advisor_campaign');
    echo $this->getChildHtml('feedback_campaign');
endif; ?>

<?php echo $this->getChildHtml('breadcrumbs') ?>

<p id="ff-nothing-found">
    <?php echo $this->escapeHtml($this->__('Your search returns no results.')) ?>
</p>

<div class="category-products">
    <?php echo $this->getChildHtml('toolbar') ?>

    <ff-record-list class="clearfix" unresolved>
        <ff-record>
            <a data-anchor="{{record.ProductUrl}}" data-redirect="{{record.ProductUrl}}" data-redirect-target="_self" class="product-name result-product-name">
                <img data-image="{{record.ImageName}}" alt="{{record.Name}}" class="product-image">
                <h2 class="result-product-name">{{record.Name}}</h2>
            </a>

            <div class="priceContainer">
                <span class="brand">{{record.Manufacturer}}</span>
                <span class="price">{{record.Price}}</span>
            </div>

            <div class="actions">
                <a title="View Details" class="button" data-anchor="{{record.ProductUrl}}" data-redirect="{{record.ProductUrl}}" data-redirect-target="_self"><?php echo $this->__('View Details'); ?></a>
            </div>
        </ff-record>
    </ff-record-list>

    <?php echo $this->getChildHtml('paging') ?>
</div>

<script>
    document.addEventListener('ffReady', function () {
        factfinder.communication.ResultDispatcher.subscribe('result', function (result) {
            if (result.resultStatus === 'nothingFound') {
                document.querySelector('.category-products').style.display = 'none';
                document.getElementById('ff-nothing-found').style.display = 'block';
            } else {
                document.querySelector('.category-products').style.display = 'block';
                document.getElementById('ff-nothing-found').style.display = 'none';
            }
        });
    });
</script>
