<?php
/** @var Omikron_Factfinder_Helper_Data $dataHelper */
/** @var Mage_Core_Block_Template $this */
$dataHelper = Mage::helper('factfinder/data');
?>

<div id="search_mini_form">
    <div class="input-box">
        <ff-searchbox class="ff-searchbox"
                      suggest-onfocus="false"
                      use-suggest="true"
                      select-onclick="true"
                      class="input-text required-entry"
                      type="search"
                      >
            <input autocomplete="off" id="search" placeholder="<?php echo $this->escapeHtml($this->__('Search...')) ?>" />
        </ff-searchbox>

        <ff-searchbutton>
            <button class="button search-button"><?php echo $this->escapeHtml($this->__('Search')) ?></button>
        </ff-searchbutton>
    </div>
</div>

<?php if ($dataHelper->getFFSuggest()): ?>
    <ff-suggest layout="block" unresolved>
        <section id="searchContainer" class="searchTermContainer">
            <div data-container="searchTerm">
                <p class="containerCaption"><?php echo $this->escapeHtml($this->__('Suggestions')) ?></p>
                <ff-suggest-item type="searchTerm">
                    <span>{{{name}}}</span>
                </ff-suggest-item>
            </div>

            <div data-container="category">
                <p class="containerCaption"><?php echo $this->escapeHtml($this->__('Categories')) ?></p>
                <ff-suggest-item type="category">
                    <span class="ff-suggest-parent-category">{{attributes.parentCategory}} ></span><span> {{{name}}}</span>
                </ff-suggest-item>
            </div>

            <div data-container="brand">
                <p class="containerCaption"><?php echo $this->escapeHtml($this->__('Brands')) ?></p>
                <ff-suggest-item type="brand">
                    <span>{{{name}}}</span>
                </ff-suggest-item>
            </div>
        </section>

        <section id="productContainer" class="productsContainer">
            <div data-container="productName">
                <p class="containerCaption"><?php echo $this->escapeHtml($this->__('Suggested products')) ?></p>
                <div>
                    <ff-suggest-item type="productName" onclick="changeSearchTerm(this)">
                        <div class="product-img"><img data-image></div>
                        <div class="product-info">
                            <div class="product-name">{{{name}}}</div>
                            <div class="price">{{attributes.Price}}</div>
                        </div>
                    </ff-suggest-item>
                </div>
            </div>
        </section>
    </ff-suggest>
<?php endif; ?>
