<?php
/** @var Omikron_Factfinder_Helper_Data $dataHelper */
$dataHelper = Mage::helper('factfinder/data');

if ($dataHelper->getFFAsn()) {
?>
   <ff-asn align="vertical" unresolved>
        <ff-asn-group for-group="all" class="cursor">
            <ff-asn-group-element>
                <div data-selected>
                    <input type="checkbox" checked>
                    <span class="filterName">{{element.name}} <span>({{element.recordCount}})</span></span>
                </div>
                <div data-unselected>
                    <input type="checkbox">
                    <span class="filterName">{{element.name}} <span>({{element.recordCount}})</span></span>
                </div>
            </ff-asn-group-element>
            <div data-container="groupCaption" class="groupCaption">{{group.name}}</div>
            <div opened data-container="detailedLinks">
                <div data-content="detailedLinks"></div>

                <div data-container="showMore">
                    <span class="text"><?php echo $this->__('Show More'); ?></span>
                </div>

                <div class="marginBottom"></div>
            </div>
            <div data-container="hiddenLinks">
                <div data-content="hiddenLinks"></div>

                <div data-container="showLess">
                    <span class="text"><?php echo $this->__('Show Less'); ?></span>
                </div>
                <div class="marginBottom"></div>
            </div>
        </ff-asn-group>
        <ff-asn-group filter-style="TREE" opened class="cursor">
            <ff-asn-group-element>
                <div data-selected>
                    &nbsp;&nbsp;<span class="filterName"><b>{{element.name}} <span>({{element.recordCount}})</span></b></span>
                </div>
                <div data-unselected>
                    <span class="filterName">{{element.name}} <span>({{element.recordCount}})</span></span>
                </div>
            </ff-asn-group-element>
            <div data-container="groupCaption" class="groupCaption">{{group.name}}</div>
            <div opened data-container="detailedLinks">
                <div data-content="detailedLinks"></div>
                <div class="marginBottom"></div>
            </div>
        </ff-asn-group>
        <ff-asn-group-slider>
           <div data-container="groupCaption" class="groupCaption">
               {{group.name}}<span class="filterArrowDown">&nbsp;</span>
           </div>
           <ff-slider-control submit-on-input="true">
               <input data-control='1' class="ff-slider-control-left">
               <input data-control='2' class="ff-slider-control-right">
               <ff-slider current-min-value="0">
                   <div data-slider="1" class="sliderBtn"></div>
                   <div data-slider="2" class="sliderBtn"></div>
               </ff-slider>
           </ff-slider-control>
            <div data-container="removeFilter">Remove Filter</div>
       </ff-asn-group-slider>
    </ff-asn>
<?php } ?>
