<?php
/** @var Mage_Core_Block_Template $this */
/** @var Omikron_Factfinder_Helper_Data $dataHelper */
/** @var Omikron_Factfinder_Model_Config_Communication $communicationConfig */
/** @var Omikron_Factfinder_Model_SessionData $sessionData */
$dataHelper = Mage::helper('factfinder');
$communicationConfig = Mage::getModel('factfinder/config_communication');
$sessionData = Mage::getSingleton('factfinder/sessionData');
?>

<ff-communication
        url="<?php echo $communicationConfig->getAddress(); ?>"
        version="<?php echo $communicationConfig->getVersion(); ?>"
        channel="<?php echo $communicationConfig->getChannel(); ?>"
        search-immediate="<?php echo $this->getData('search_immediate') ? 'true' : 'false' ?>"
        use-url-parameters="<?php echo $dataHelper->getUseUrlParameter() ? 'true' : 'false' ?>"
        disable-single-hit-redirect="true"
        use-cache="<?php echo $dataHelper->getUseCache() ? 'true' : 'false' ?>"
        only-search-params="true"
        currency-code="<?php echo Mage::app()->getStore()->getDefaultCurrencyCode(); ?>"
        currency-country-code="<?php echo Mage::getStoreConfig('general/country/default'); ?>"
        <?php if ($sessionData->getUserId()): ?>
            user-id="<?php echo $sessionData->getUserId() ?>"
            sid="<?php echo $sessionData->getSessionId() ?>"
        <?php endif; ?>
        <?php if ($communicationConfig->getVersion() === 'ng'): ?>
            api="<?php echo $communicationConfig->getApi() ?>"
        <?php endif; ?>
        add-params="<?php echo implode(',', array_filter([$dataHelper->getAddParams(), $this->getData('add-params')])) ?>"
        add-tracking-params="<?php echo implode(',', array_filter([$dataHelper->getAddTrackingParams(), $this->getData('add-tracking-params')])) ?>"
        keep-url-params="<?php echo implode(',', array_filter([$dataHelper->getKeepUrlParams(), $this->getData('keep-url-params')])) ?>"
        parameter-whitelist="<?php echo implode(',', array_filter([$dataHelper->getParameterWhiteList(), $this->getData('parameter-whitelist')])) ?>"
></ff-communication>

<script>
    var ffRedirectPath = '<?php echo $this->jsQuoteEscape($this->getUrl('factfinder/result')) ?>';

    document.addEventListener("ffReady", function () {
        factfinder.communication.fieldRoles = {
            displayProductNumber: "ProductNumber",
            trackingProductName: "ProductNumber",
            ean: "EAN",
            price: "Price",
            deeplink: "ProductUrl",
            imageUrl: "ImageUrl",
            campaignProductNumber: "ProductNumber",
            description: "Description",
            masterArticleNumber: "MasterProductNumber",
            brand: "Manufacturer",
            productName: "Name",
        }
    });
</script>
