<?php
/** @var Mage_Core_Block_Template $this */
/** @var Omikron_Factfinder_Helper_Data $dataHelper */
$dataHelper = Mage::helper('factfinder/data');
?>

<ff-communication
        url="<?php echo $dataHelper->getAddress(); ?>"
        version="<?php echo $dataHelper->getVersion(); ?>"
        channel="<?php echo $dataHelper->getChannel(); ?>"
        search-immediate="<?php echo $this->getData('search_immediate') ? 'true' : 'false' ?>"
        use-url-parameter="<?php echo $dataHelper->getUseUrlParameter() ? 'true' : 'false' ?>"
        <?php if($dataHelper->getUseCache()):
            echo 'use-cache';
        endif; ?>
        disable-cache="<?php echo $dataHelper->getDisableCache() ? 'true' : 'false' ?>"
        default-query="<?php echo $dataHelper->getDefaultQuery(); ?>"
        use-asn="<?php echo $dataHelper->getUseAsn() ? 'true' : 'false' ?>"
        use-found-rows="<?php echo $dataHelper->getUseFoundWords() ? 'true' : 'false' ?>"
        use-campaigns="<?php echo $dataHelper->getFFCampaign() ? 'true' : 'false' ?>"
        use-personalization="<?php echo $dataHelper->getUsePersonalization() ? 'true' : 'false' ?>"
        use-semantic-enhancer="<?php echo $dataHelper->getUseSemanticEnhancer() ? 'true' : 'false' ?>"
        use-aso="<?php echo $dataHelper->getUseAso() ? 'true' : 'false' ?>"
        use-browser-history="<?php echo $dataHelper->getUseBrowserHistory() ? 'true' : 'false' ?>"
        use-seo="<?php echo $dataHelper->getUseSeo() ? 'true' : 'false' ?>"
        seo-prefix="<?php echo $dataHelper->getSeoPrefix(); ?>"
        <?php if($dataHelper->getOnlySearchParams()):
            echo 'only-search-params';
        endif; ?>
        currency-code="<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>"
        currency-country-code="<?php echo Mage::getStoreConfig('general/country/default'); ?>"
        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()):
            echo 'user-id="' . Mage::getSingleton('customer/session')->getId() . '"';
        endif; ?>
        add-params="<?php echo implode(',', array_filter([$dataHelper->getAddParams(), $this->getData('add-params')])) ?>"
        add-tracking-params="<?php echo implode(',', array_filter([$dataHelper->getAddTrackingParams(), $this->getData('add-tracking-params')])) ?>"
        keep-url-params="<?php echo implode(',', array_filter([$dataHelper->getKeepUrlParams(), $this->getData('keep-url-params')])) ?>"
        parameter-whitelist="<?php echo implode(',', array_filter([$dataHelper->getParameterWhiteList(), $this->getData('parameter-whitelist')])) ?>"
></ff-communication>

<script>
    var ffRedirectPath = '<?php echo $this->jsQuoteEscape($this->getUrl('factfinder/result')) ?>';

    document.addEventListener("ffReady", function () {
        factfinder.communication.fieldRoles = {
            displayProductNumber: "ProductNumber",
            trackingProductName: "ProductNumber",
            ean: "EAN",
            price: "Price",
            deeplink: "ProductUrl",
            imageUrl: "ImageUrl",
            campaignProductNumber: "ProductNumber",
            description: "Description",
            masterArticleNumber: "MasterProductNumber",
            brand: "Manufacturer",
            productName: "Name",
        }
    });
</script>
