<style>
    [unresolved] {
        opacity: 0;
        display: none;
    }
</style>
<script  src="<?php echo Mage::getBaseUrl('js'); ?>factfinder/ff-web-components/vendor/custom-elements-es5-adapter.js"></script>
<script src="<?php echo Mage::getBaseUrl('js'); ?>factfinder/ff-web-components/vendor/webcomponents-loader.js"></script>
<script defer src="<?php echo Mage::getBaseUrl('js'); ?>factfinder/ff-web-components/bundle.js"></script>