<?php

if ($parentId = $this->getProductParentIdByProductId(Mage::getSingleton('core/session')->getData('ff_add_to_cart_id'))) {
    $parentProduct = Mage::getModel('catalog/product')->load($parentId);
    $masterProduct = $parentProduct->getSku();
} else {
    $masterProduct = Mage::getSingleton('core/session')->getData('ff_add_to_cart_sku');
}
?>

<?php if (Mage::getSingleton('core/session')->getData('ff_add_to_cart_sku')) { ?>
    <script>
        document.addEventListener("WebComponentsReady", function () {
            var tracking = new factfinder.communication.Tracking12();
            tracking.cart({
                id: "<?php echo Mage::getSingleton('core/session')->getData('ff_add_to_cart_sku'); ?>",
                price: "<?php echo Mage::getSingleton('core/session')->getData('ff_add_to_cart_price'); ?>",
                masterId: "<?php echo $masterProduct; ?>",
                <?php if(Mage::getSingleton('customer/session')->isLoggedIn()) {
                    echo 'userId: "' . Mage::getSingleton('customer/session')->getId() . '",';
                } ?>
                count: "<?php echo Mage::getSingleton('core/session')->getData('ff_add_to_cart_qty'); ?>"
            });
        });
    </script>
<?php } ?>

<?php
Mage::getSingleton('core/session')->unsetData('ff_add_to_cart_id');
Mage::getSingleton('core/session')->unsetData('ff_add_to_cart_sku');
Mage::getSingleton('core/session')->unsetData('ff_add_to_cart_price');
Mage::getSingleton('core/session')->unsetData('ff_add_to_cart_qty');
