<script type="text/javascript">
    function checkTestConnection() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'post',
            parameters: {
                serverUrl: document.getElementById('factfinder_general_address').value,
                channel:  document.getElementById('factfinder_general_channel').value,
                username: document.getElementById('factfinder_general_username').value,
                password: document.getElementById('factfinder_general_password').value,
                authenticationPrefix: document.getElementById('factfinder_general_authentication_prefix').value,
                authenticationPostfix: document.getElementById('factfinder_general_authentication_postfix').value
            },
            onSuccess: function (transport) {
                var response = JSON.parse(transport.responseText);
                setFFCommunicationInfoMessage(response.message);
            },
            onFailure: function (transport) {
                setFFCommunicationInfoMessage('<?php echo $this->__('There were an error during test connection. Please check if You provide all required authorization data') ?>');
            }
        });
    }

    function setFFCommunicationInfoMessage(message) {
        document.getElementById("ffCommunicationInfo").innerHTML = message;
    }
</script>

<?php echo $this->getButtonHtml() ?>
<p id="ffCommunicationInfo"></p>

