<script type="text/javascript">
    function checkTestConnection() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'get',
            onSuccess: function (transport) {
                var response = JSON.parse(transport.responseText);
                setFFCommunicationInfoMessage(response.message);
            },
            onFailure: function (transport) {
                setFFCommunicationInfoMessage('<?php echo(__("There were an error during test connection. Please check if You provide all required authorization data")) ?>');
            }
        });
    }

    function setFFCommunicationInfoMessage(message) {
        document.getElementById("ffCommunicationInfo").innerHTML = message;
    }
</script>

<?php echo $this->getButtonHtml() ?>
<p id="ffCommunicationInfo"></p>

