<script type="text/javascript">
    function uploadCsv() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'get',
            onSuccess: function (transport) {
                var response = JSON.parse(transport.responseText);
                setUploadCsvMessage(response.message.message);
            },
            onFailure: function (transport) {
                setUploadCsvMessage(<?php echo(__("There were an error during feed upload. Please check the server log and contact the technical support.")) ?>);
            }
        });
    }

    function setUploadCsvMessage(message) {
        document.getElementById("ffUploadInfo").innerHTML = message;
    }
</script>

<?php echo $this->getButtonHtml() ?>
<p id="ffUploadInfo"></p>

