<?php /* @var Omikron_Factfinder_Block_Adminhtml_System_Config_Button_Upload $this */ ?>
<script type="text/javascript">
    function uploadCsv() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'get',
            onSuccess: function (transport) {
                var response = transport.responseJSON || transport.responseText.evalJSON(true) || {};
                setUploadCsvMessage(response.message.message);
            },
            onFailure: function () {
                setUploadCsvMessage('<?php echo $this->jsQuoteEscape($this->__('There were an error during feed upload. Please check the server log and contact the technical support.')) ?>');
            }
        });
    }

    function setUploadCsvMessage(message) {
        document.getElementById('ffUploadInfo').update(message);
    }
</script>

<?php echo $this->getButtonHtml() ?>
<p id="ffUploadInfo"></p>
