<?php /** @var $this Mage_Core_Block_Template */ ?>
<div class="ff-breadcrumbs ">
    <h1><?php echo $this->escapeHtml($this->__('Search results for')) ?>:
        <ff-breadcrumb-trail unresolved>
            <ff-breadcrumb-trail-item type="search">
                <span>{{text}}</span>
            </ff-breadcrumb-trail-item>
            <ff-breadcrumb-trail-item type="filter">
                <span>{{text}}</span>
            </ff-breadcrumb-trail-item>
            <ff-breadcrumb-trail-item type="advisor">
                <span>{{text}}</span>
            </ff-breadcrumb-trail-item>
        </ff-breadcrumb-trail>
    </h1>
</div>
