<?php /** @var Mage_Core_Block_Template $this */ ?>
<ff-paging unresolved>
    <ff-paging-item type="currentLink -2" class="ff-link">{{caption}}</ff-paging-item>
    <ff-paging-item type="currentLink -1" class="ff-link">{{caption}}</ff-paging-item>
    <ff-paging-item type="currentLink" class="ff-current-link">{{caption}}</ff-paging-item>
    <ff-paging-item type="currentLink +1" class="ff-link">{{caption}}</ff-paging-item>
    <ff-paging-item type="currentLink +2" class="ff-link">{{caption}}</ff-paging-item>
</ff-paging>
