<?php
/** @var Mage_Core_Block_Template $this */
/** @var Mage_Sales_Model_Order $order */
/** @var Mage_Sales_Model_Order_Item $item */
$order = Mage::getSingleton('checkout/session')->getLastRealOrder();
?>
<ff-checkout-tracking>
<?php foreach ($order->getAllVisibleItems() as $item): ?>
    <ff-checkout-tracking-item record-id="<?php echo $this->escapeHtml($item->getProduct()->getData('sku')) ?>"
                               count="<?php echo (int) $item->getQtyOrdered() ?>"></ff-checkout-tracking-item>
<?php endforeach; ?>
</ff-checkout-tracking>

